# Generated by Django 5.1.2 on 2025-02-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('rating', models.FloatField()),
                ('poster_path', models.URLField(max_length=500)),
                ('category', models.CharField(max_length=255)),
                ('tmdb_id', models.IntegerField(unique=True)),
            ],
        ),
    ]
